package navigation

import (
	"database/sql"
	"fmt"
	"html"
	"log"
	"strings"
	"time"
)

// InitNavSchema creates the navigation tables and indexes in db.
// Uses IF NOT EXISTS so it is safe to call on an already-initialised database.
func InitNavSchema(db *sql.DB) error {
	_, err := db.Exec(`
		CREATE TABLE IF NOT EXISTS nav_folders (
			id                 INTEGER PRIMARY KEY AUTOINCREMENT,
			path               TEXT    UNIQUE NOT NULL,
			parent_id          INTEGER,
			display_name       TEXT    NOT NULL,
			description        TEXT    DEFAULT '',
			description_source TEXT    DEFAULT 'auto',
			is_leaf            BOOLEAN DEFAULT 0,
			child_count        INTEGER DEFAULT 0,
			guide_count        INTEGER DEFAULT 0,
			content_type       TEXT    DEFAULT '',
			last_scanned       DATETIME,
			created_at         DATETIME DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(parent_id) REFERENCES nav_folders(id)
		);
		CREATE TABLE IF NOT EXISTS nav_guides (
			id            INTEGER PRIMARY KEY AUTOINCREMENT,
			folder_id     INTEGER NOT NULL,
			file_name     TEXT    NOT NULL,
			file_path     TEXT    UNIQUE NOT NULL,
			title         TEXT    DEFAULT '',
			preview       TEXT    DEFAULT '',
			word_count    INTEGER DEFAULT 0,
			last_modified DATETIME,
			FOREIGN KEY(folder_id) REFERENCES nav_folders(id) ON DELETE CASCADE
		);
		CREATE TABLE IF NOT EXISTS nav_description_overrides (
			id                 INTEGER PRIMARY KEY AUTOINCREMENT,
			folder_id          INTEGER NOT NULL UNIQUE,
			custom_description TEXT    NOT NULL,
			override_by        TEXT    DEFAULT '',
			override_date      DATETIME DEFAULT CURRENT_TIMESTAMP,
			FOREIGN KEY(folder_id) REFERENCES nav_folders(id) ON DELETE CASCADE
		);
		CREATE TABLE IF NOT EXISTS nav_guide_tags (
			guide_id INTEGER NOT NULL,
			tag      TEXT    NOT NULL,
			PRIMARY KEY (guide_id, tag),
			FOREIGN KEY(guide_id) REFERENCES nav_guides(id) ON DELETE CASCADE
		);
		-- Wikilink edges between notes. Like the FTS index below, this table is
		-- fully regenerated by the scanner inside the scan transaction (see
		-- rebuildLinks in links.go) — it is never incrementally maintained, so it
		-- never holds rows for pruned guides. target_id is NULL when the wikilink
		-- target resolves to no local note (a broken link / vault gap).
		CREATE TABLE IF NOT EXISTS nav_links (
			id          INTEGER PRIMARY KEY AUTOINCREMENT,
			source_id   INTEGER NOT NULL,
			target_path TEXT    NOT NULL,
			target_id   INTEGER,
			kind        TEXT    NOT NULL DEFAULT 'link',
			FOREIGN KEY(source_id) REFERENCES nav_guides(id) ON DELETE CASCADE
		);
		CREATE INDEX IF NOT EXISTS idx_nav_links_source       ON nav_links(source_id);
		CREATE INDEX IF NOT EXISTS idx_nav_links_target       ON nav_links(target_id);
		CREATE INDEX IF NOT EXISTS idx_nav_links_target_path  ON nav_links(target_path);

		CREATE INDEX IF NOT EXISTS idx_nav_folders_path         ON nav_folders(path);
		CREATE INDEX IF NOT EXISTS idx_nav_folders_parent       ON nav_folders(parent_id);
		CREATE INDEX IF NOT EXISTS idx_nav_folders_content_type ON nav_folders(content_type);
		CREATE INDEX IF NOT EXISTS idx_nav_guides_folder        ON nav_guides(folder_id);
		CREATE INDEX IF NOT EXISTS idx_nav_guides_file_path     ON nav_guides(file_path);
		CREATE INDEX IF NOT EXISTS idx_nav_guide_tags_tag       ON nav_guide_tags(tag);
		CREATE INDEX IF NOT EXISTS idx_nav_guide_tags_guide     ON nav_guide_tags(guide_id);

		-- Full-text search index over note titles and previews. This is an
		-- external-content FTS5 table (content='nav_guides'): it stores only the
		-- token index, reading the actual text from nav_guides at query time, so
		-- there is no data duplication. It is NOT kept in sync by triggers — the
		-- scanner rebuilds it explicitly at the end of each scan (see scanner.go),
		-- which is simplest given the index is fully regenerated on every scan.
		CREATE VIRTUAL TABLE IF NOT EXISTS nav_fts
			USING fts5(title, preview, content='nav_guides', content_rowid='id');
	`)
	if err != nil {
		return fmt.Errorf("nav schema init: %w", err)
	}

	// Backward-compatible column additions. SQLite has no ADD COLUMN IF NOT
	// EXISTS, so each is wrapped to ignore the duplicate-column error on
	// databases that already have it.
	addNavColumn(db, "nav_folders", "sort_order", "INTEGER DEFAULT 0")
	addNavColumn(db, "nav_folders", "hide_from_nav", "BOOLEAN DEFAULT 0")

	log.Println("[Navigation] Schema ready")
	return nil
}

// addNavColumn runs an ALTER TABLE ADD COLUMN, ignoring the error raised when
// the column is already present (so it is safe to call on every startup).
func addNavColumn(db *sql.DB, table, col, def string) {
	_, err := db.Exec(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", table, col, def))
	if err != nil && !strings.Contains(err.Error(), "duplicate column name") {
		log.Printf("[Navigation] add column %s.%s: %v", table, col, err)
	}
}

// GetNavigationTree returns a folder with its full subtree populated recursively.
func (s *Service) GetNavigationTree(path string) (*NavNode, error) {
	var node NavNode
	err := s.db.QueryRow(`
		SELECT id, path, display_name,
		       COALESCE(description,''), COALESCE(description_source,'auto'),
		       is_leaf, child_count, guide_count, COALESCE(content_type,'')
		FROM nav_folders WHERE path = ?`, path).
		Scan(&node.ID, &node.Path, &node.DisplayName, &node.Description,
			&node.DescriptionSrc, &node.IsLeaf, &node.ChildCount,
			&node.GuideCount, &node.ContentType)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("folder not found: %s", path)
	}
	if err != nil {
		return nil, fmt.Errorf("query nav_folders: %w", err)
	}
	// Always load children: subfolders AND the folder's own .md files (as guide
	// nodes). A leaf folder has no subfolders but still holds the files the UI
	// needs to list, so this must run regardless of is_leaf.
	children, err := s.getChildren(s.db, node.ID)
	if err != nil {
		return nil, err
	}
	node.Children = children
	return &node, nil
}

func (s *Service) getChildren(dbtx DBTX, parentID int64) ([]NavNode, error) {
	rows, err := dbtx.Query(`
		SELECT id, path, display_name,
		       COALESCE(description,''), COALESCE(description_source,'auto'),
		       is_leaf, child_count, guide_count, COALESCE(content_type,'')
		FROM nav_folders WHERE parent_id = ? ORDER BY display_name`, parentID)
	if err != nil {
		return nil, fmt.Errorf("query children: %w", err)
	}
	defer rows.Close()

	var children []NavNode
	for rows.Next() {
		var c NavNode
		if err := rows.Scan(&c.ID, &c.Path, &c.DisplayName, &c.Description,
			&c.DescriptionSrc, &c.IsLeaf, &c.ChildCount, &c.GuideCount, &c.ContentType); err != nil {
			log.Printf("[Navigation] scan child row: %v", err)
			continue
		}
		sub, err := s.getChildren(dbtx, c.ID)
		if err == nil {
			c.Children = sub
		}
		children = append(children, c)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	// Append this folder's indexed .md files as leaf guide nodes so the UI can
	// list the articles inside it, not just its subfolders.
	guides, err := s.getGuides(dbtx, parentID)
	if err != nil {
		return nil, err
	}
	return append(children, guides...), nil
}

// getGuides returns a folder's indexed .md files as leaf guide nodes. The .md
// extension is dropped from path so it matches the article paths used elsewhere
// (breadcrumbs, recent files); /api/content resolves either form.
func (s *Service) getGuides(dbtx DBTX, folderID int64) ([]NavNode, error) {
	rows, err := dbtx.Query(`
		SELECT id, file_path, COALESCE(title, '')
		FROM nav_guides WHERE folder_id = ? ORDER BY title, file_path`, folderID)
	if err != nil {
		return nil, fmt.Errorf("query guides: %w", err)
	}
	defer rows.Close()

	var guides []NavNode
	for rows.Next() {
		var g NavNode
		var filePath, title string
		if err := rows.Scan(&g.ID, &filePath, &title); err != nil {
			log.Printf("[Navigation] scan guide row: %v", err)
			continue
		}
		if dot := strings.LastIndex(filePath, "."); dot >= 0 && strings.EqualFold(filePath[dot:], ".md") {
			filePath = filePath[:dot]
		}
		g.Path = filePath
		g.DisplayName = title
		if g.DisplayName == "" {
			g.DisplayName = filePath
		}
		g.IsLeaf = true
		g.IsGuide = true
		guides = append(guides, g)
	}
	return guides, rows.Err()
}

// GetNavigationFlat returns an ordered flat list of folders, optionally filtered
// by path prefix and/or content_type (vault name).
func (s *Service) GetNavigationFlat(path, contentType string) ([]NavNode, error) {
	q := `SELECT id, path, display_name, COALESCE(description,''),
	             is_leaf, child_count, guide_count, COALESCE(content_type,'')
	      FROM nav_folders`
	var args []any
	var where []string
	if path != "" {
		where = append(where, "path LIKE ?")
		args = append(args, path+"%")
	}
	if contentType != "" {
		where = append(where, "content_type = ?")
		args = append(args, contentType)
	}
	if len(where) > 0 {
		q += " WHERE " + strings.Join(where, " AND ")
	}
	q += " ORDER BY path"

	rows, err := s.db.Query(q, args...)
	if err != nil {
		return nil, fmt.Errorf("query nav_folders flat: %w", err)
	}
	defer rows.Close()

	var nodes []NavNode
	for rows.Next() {
		var n NavNode
		if err := rows.Scan(&n.ID, &n.Path, &n.DisplayName, &n.Description,
			&n.IsLeaf, &n.ChildCount, &n.GuideCount, &n.ContentType); err != nil {
			log.Printf("[Navigation] scan flat row: %v", err)
			continue
		}
		nodes = append(nodes, n)
	}
	return nodes, rows.Err()
}

// upsertFolder inserts or updates a folder record; returns its stable ID.
func (s *Service) upsertFolder(dbtx DBTX, path, displayName, description, contentType string, parentID *int64, isLeaf bool) (int64, error) {
	_, err := dbtx.Exec(`
		INSERT INTO nav_folders
			(path, parent_id, display_name, description, description_source, is_leaf, content_type, last_scanned)
		VALUES (?, ?, ?, ?, 'auto', ?, ?, CURRENT_TIMESTAMP)
		ON CONFLICT(path) DO UPDATE SET
			display_name  = excluded.display_name,
			is_leaf       = excluded.is_leaf,
			content_type  = excluded.content_type,
			last_scanned  = excluded.last_scanned
	`, path, parentID, displayName, description, isLeaf, contentType)
	if err != nil {
		return 0, fmt.Errorf("upsert folder %s: %w", path, err)
	}
	var id int64
	if err := dbtx.QueryRow(`SELECT id FROM nav_folders WHERE path = ?`, path).Scan(&id); err != nil {
		return 0, fmt.Errorf("fetch id for %s: %w", path, err)
	}
	return id, nil
}

// upsertGuide inserts or updates an indexed .md file record and returns its stable ID.
func (s *Service) upsertGuide(dbtx DBTX, folderID int64, fileName, filePath, title, preview string, wordCount int, lastModified time.Time) (int64, error) {
	_, err := dbtx.Exec(`
		INSERT INTO nav_guides (folder_id, file_name, file_path, title, preview, word_count, last_modified)
		VALUES (?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(file_path) DO UPDATE SET
			folder_id     = excluded.folder_id,
			title         = excluded.title,
			preview       = excluded.preview,
			word_count    = excluded.word_count,
			last_modified = excluded.last_modified
	`, folderID, fileName, filePath, title, preview, wordCount, lastModified)
	if err != nil {
		return 0, err
	}
	var id int64
	if err := dbtx.QueryRow(`SELECT id FROM nav_guides WHERE file_path = ?`, filePath).Scan(&id); err != nil {
		return 0, fmt.Errorf("fetch id for guide %s: %w", filePath, err)
	}
	return id, nil
}

// setGuideTags replaces the tag set for a guide (delete-then-insert) so a rescan
// reflects the note's current red_tags.
func (s *Service) setGuideTags(dbtx DBTX, guideID int64, tags []string) error {
	if _, err := dbtx.Exec(`DELETE FROM nav_guide_tags WHERE guide_id = ?`, guideID); err != nil {
		return fmt.Errorf("clear tags for guide %d: %w", guideID, err)
	}
	for _, tag := range tags {
		if _, err := dbtx.Exec(
			`INSERT OR IGNORE INTO nav_guide_tags (guide_id, tag) VALUES (?, ?)`, guideID, tag); err != nil {
			return fmt.Errorf("insert tag %q for guide %d: %w", tag, guideID, err)
		}
	}
	return nil
}

// GetAllTags returns every distinct tag with the number of guides carrying it,
// ordered by descending count then name.
func (s *Service) GetAllTags() ([]TagCount, error) {
	rows, err := s.db.Query(`
		SELECT tag, COUNT(*) AS n FROM nav_guide_tags
		GROUP BY tag ORDER BY n DESC, tag ASC`)
	if err != nil {
		return nil, fmt.Errorf("query tags: %w", err)
	}
	defer rows.Close()

	tags := []TagCount{}
	for rows.Next() {
		var t TagCount
		if err := rows.Scan(&t.Name, &t.Count); err != nil {
			log.Printf("[Navigation] scan tag row: %v", err)
			continue
		}
		tags = append(tags, t)
	}
	return tags, rows.Err()
}

// GetNotesByTag returns the guide nodes tagged with tag, as leaf is_guide nodes
// (same shape getChildren emits) so the UI can render them like any article list.
func (s *Service) GetNotesByTag(tag string) ([]NavNode, error) {
	rows, err := s.db.Query(`
		SELECT g.id, g.file_path, COALESCE(g.title, '')
		FROM nav_guides g
		JOIN nav_guide_tags t ON t.guide_id = g.id
		WHERE t.tag = ? ORDER BY g.title, g.file_path`, tag)
	if err != nil {
		return nil, fmt.Errorf("query notes by tag: %w", err)
	}
	defer rows.Close()

	notes := []NavNode{}
	for rows.Next() {
		var n NavNode
		var filePath, title string
		if err := rows.Scan(&n.ID, &filePath, &title); err != nil {
			log.Printf("[Navigation] scan tagged note: %v", err)
			continue
		}
		n.Path = strings.TrimSuffix(filePath, ".md")
		n.DisplayName = title
		if n.DisplayName == "" {
			n.DisplayName = n.Path
		}
		n.IsLeaf = true
		n.IsGuide = true
		notes = append(notes, n)
	}
	return notes, rows.Err()
}

// SearchResult is one hit from a full-text search: the note's path (without the
// .md extension, matching the form used everywhere else in the UI), its title,
// and a snippet of the matching preview with the matched terms wrapped in <mark>.
type SearchResult struct {
	FilePath string `json:"file_path"`
	Title    string `json:"title"`
	Snippet  string `json:"snippet"`
}

// Snippet highlight markers. SQLite wraps matched terms in these control-char
// sentinels (which cannot meaningfully occur in note text); after the raw snippet
// is HTML-escaped we swap them for live <mark> tags. This guarantees the only
// unescaped HTML reaching the client (which renders snippets with v-html) is our
// own highlight markup — never raw note content. See snippetToSafeHTML.
const (
	snipOpenSentinel  = "\x01"
	snipCloseSentinel = "\x02"
)

// snippetToSafeHTML turns a raw FTS snippet (note content interleaved with the
// highlight sentinels above) into HTML that is safe to render with v-html: the
// content is HTML-escaped, then the sentinels become <mark>/</mark>.
func snippetToSafeHTML(raw string) string {
	escaped := html.EscapeString(raw)
	return strings.NewReplacer(
		snipOpenSentinel, "<mark>",
		snipCloseSentinel, "</mark>",
	).Replace(escaped)
}

// SearchGuides runs an FTS5 full-text query over note titles and previews and
// returns up to 20 results ranked by relevance. query is passed straight to
// FTS5's MATCH, so it supports FTS5 syntax (phrases, prefixes, AND/OR/NOT). The
// snippet is drawn from the preview column (index 1); matched terms are wrapped
// in <mark> for client-side highlighting after the surrounding content has been
// HTML-escaped, so attacker-supplied note text cannot inject markup.
func (s *Service) SearchGuides(query string) ([]SearchResult, error) {
	rows, err := s.db.Query(`
		SELECT g.file_path, g.title,
		       snippet(nav_fts, 1, ?, ?, '…', 15)
		FROM nav_fts
		JOIN nav_guides g ON g.id = nav_fts.rowid
		WHERE nav_fts MATCH ?
		ORDER BY rank
		LIMIT 20`, snipOpenSentinel, snipCloseSentinel, query)
	if err != nil {
		return nil, fmt.Errorf("fts search: %w", err)
	}
	defer rows.Close()

	var out []SearchResult
	for rows.Next() {
		var r SearchResult
		if err := rows.Scan(&r.FilePath, &r.Title, &r.Snippet); err != nil {
			log.Printf("[Navigation] scan search row: %v", err)
			continue
		}
		r.FilePath = strings.TrimSuffix(r.FilePath, ".md")
		r.Snippet = snippetToSafeHTML(r.Snippet)
		out = append(out, r)
	}
	return out, rows.Err()
}

// updateAggregates recalculates child_count and guide_count for every folder.
func (s *Service) updateAggregates(dbtx DBTX) error {
	if _, err := dbtx.Exec(`
		UPDATE nav_folders SET child_count = (
			SELECT COUNT(*) FROM nav_folders c WHERE c.parent_id = nav_folders.id
		)`); err != nil {
		return fmt.Errorf("update child_count: %w", err)
	}
	// Count guides in the entire subtree (self + all descendants) using path-prefix
	// matching so non-leaf vault cards show a meaningful total, not 0.
	if _, err := dbtx.Exec(`
		UPDATE nav_folders SET guide_count = (
			SELECT COUNT(*) FROM nav_guides g
			JOIN nav_folders f ON f.id = g.folder_id
			WHERE f.path = nav_folders.path
			   OR f.path LIKE nav_folders.path || '/%'
		)`); err != nil {
		return fmt.Errorf("update guide_count: %w", err)
	}
	return nil
}

// GetFolderByID retrieves a single folder by its database ID.
func (s *Service) GetFolderByID(id int64) (*NavNode, error) {
	var n NavNode
	err := s.db.QueryRow(`
		SELECT id, path, display_name, COALESCE(description,''),
		       is_leaf, child_count, guide_count, COALESCE(content_type,'')
		FROM nav_folders WHERE id = ?`, id).
		Scan(&n.ID, &n.Path, &n.DisplayName, &n.Description,
			&n.IsLeaf, &n.ChildCount, &n.GuideCount, &n.ContentType)
	if err != nil {
		return nil, err
	}
	return &n, nil
}

// SetFolderDescription persists a custom description override and updates the folder record.
func (s *Service) SetFolderDescription(folderID int64, description, overrideBy string) error {
	_, err := s.db.Exec(`
		INSERT INTO nav_description_overrides (folder_id, custom_description, override_by)
		VALUES (?, ?, ?)
		ON CONFLICT(folder_id) DO UPDATE SET
			custom_description = excluded.custom_description,
			override_by        = excluded.override_by,
			override_date      = CURRENT_TIMESTAMP
	`, folderID, description, overrideBy)
	if err != nil {
		return err
	}
	_, err = s.db.Exec(`
		UPDATE nav_folders SET description = ?, description_source = 'override' WHERE id = ?`,
		description, folderID)
	return err
}
